# Generated by Django 3.2.3 on 2024-01-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_cart_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredient',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
